// (c) Magic Mango and individual authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by internal/config/generate.
// DO NOT EDIT.

package configs

import (
	"fmt"
	"github.com/spf13/viper"
	"os"
	"strings"
)

var ErrNotDefined = fmt.Errorf("variable not defined")

func init() {
	// Automatically bind environment variables.
	viper.AutomaticEnv()
}

const (
	API_KEY             = "MANGOMAIL_API_KEY"
	HTTP_ADDRESS        = "MANGOMAIL_HTTP_ADDRESS"
	HTTP_MAX_RETRIES    = "MANGOMAIL_HTTP_MAX_RETRIES"
	HTTP_RETRY_INTERVAL = "MANGOMAIL_HTTP_RETRY_INTERVAL"
	MAX_STARTUP_TIME    = "MANGOMAIL_MAX_STARTUP_TIME"
	TELEMETRY_ADDRESS   = "MANGOMAIL_TELEMETRY_ADDRESS"
	RESEND_API_KEY      = "MANGOMAIL_RESEND_API_KEY"
	RESEND_RATE_LIMIT   = "MANGOMAIL_RESEND_RATE_LIMIT"
	LOG_COLOR           = "MANGOMAIL_LOG_COLOR"
	LOG_LEVEL           = "MANGOMAIL_LOG_LEVEL"

	// File variants
	API_KEY_FILE = "MANGOMAIL_API_KEY_FILE"

	RESEND_API_KEY_FILE = "MANGOMAIL_RESEND_API_KEY_FILE"
)

func SetDefaults() {
	// Set defaults based on the TOML definitions.

	// no default for MANGOMAIL_API_KEY

	viper.SetDefault(HTTP_ADDRESS, ":8081")

	viper.SetDefault(HTTP_MAX_RETRIES, "3")

	viper.SetDefault(HTTP_RETRY_INTERVAL, "5")

	viper.SetDefault(MAX_STARTUP_TIME, "10")

	viper.SetDefault(TELEMETRY_ADDRESS, ":8080")

	// no default for MANGOMAIL_RESEND_API_KEY

	viper.SetDefault(RESEND_RATE_LIMIT, "2")

	viper.SetDefault(LOG_COLOR, "true")

	viper.SetDefault(LOG_LEVEL, "info")

}

// MangomailConfig holds configuration values for the mangomail service.
type MangomailConfig struct {

	// API key for authenticating HTTP API requests. Can be loaded from file using MANGOMAIL_API_KEY_FILE
	ApiKey RedactedString `mapstructure:"MANGOMAIL_API_KEY"`

	// HTTP server address and port for the API server
	HttpAddress string `mapstructure:"MANGOMAIL_HTTP_ADDRESS"`

	// Maximum number of retry attempts for HTTP server startup after encountering an error.
	HttpMaxRetries int `mapstructure:"MANGOMAIL_HTTP_MAX_RETRIES"`

	// Wait time between HTTP server startup retry attempts.
	HttpRetryInterval Duration `mapstructure:"MANGOMAIL_HTTP_RETRY_INTERVAL"`

	// Maximum startup time for the service
	MaxStartupTime Duration `mapstructure:"MANGOMAIL_MAX_STARTUP_TIME"`

	// Telemetry server address and port for health checks and metrics
	TelemetryAddress string `mapstructure:"MANGOMAIL_TELEMETRY_ADDRESS"`

	// Resend API key for sending emails. Can be loaded from file using MANGOMAIL_RESEND_API_KEY_FILE
	ResendApiKey RedactedString `mapstructure:"MANGOMAIL_RESEND_API_KEY"`

	// Maximum number of email requests per second (rate limit)
	ResendRateLimit int `mapstructure:"MANGOMAIL_RESEND_RATE_LIMIT"`

	// Log color for the service
	LogColor bool `mapstructure:"MANGOMAIL_LOG_COLOR"`

	// Log level for the service (debug, info, warn, error)
	LogLevel LogLevel `mapstructure:"MANGOMAIL_LOG_LEVEL"`
}

// LoadMangomailConfig reads configuration from environment variables, a config file, and defaults.
// Priority: command line flags > environment variables > config file > defaults.
func LoadMangomailConfig() (*MangomailConfig, error) {
	SetDefaults()

	// Load config file if specified via --config flag.
	if cfgFile := viper.GetString("config"); cfgFile != "" {
		viper.SetConfigFile(cfgFile)
		if err := viper.ReadInConfig(); err != nil {
			return nil, fmt.Errorf("error reading config file: %w", err)
		}
	}

	var cfg MangomailConfig
	var err error

	cfg.ApiKey, err = GetApiKey()
	if err != nil && err != ErrNotDefined {
		return nil, fmt.Errorf("failed to get MANGOMAIL_API_KEY: %w", err)
	} else if err == ErrNotDefined {
		return nil, fmt.Errorf("MANGOMAIL_API_KEY is required for the mangomail service: %w", err)
	}

	cfg.HttpAddress, err = GetHttpAddress()
	if err != nil && err != ErrNotDefined {
		return nil, fmt.Errorf("failed to get MANGOMAIL_HTTP_ADDRESS: %w", err)
	} else if err == ErrNotDefined {
		return nil, fmt.Errorf("MANGOMAIL_HTTP_ADDRESS is required for the mangomail service: %w", err)
	}

	cfg.HttpMaxRetries, err = GetHttpMaxRetries()
	if err != nil && err != ErrNotDefined {
		return nil, fmt.Errorf("failed to get MANGOMAIL_HTTP_MAX_RETRIES: %w", err)
	} else if err == ErrNotDefined {
		return nil, fmt.Errorf("MANGOMAIL_HTTP_MAX_RETRIES is required for the mangomail service: %w", err)
	}

	cfg.HttpRetryInterval, err = GetHttpRetryInterval()
	if err != nil && err != ErrNotDefined {
		return nil, fmt.Errorf("failed to get MANGOMAIL_HTTP_RETRY_INTERVAL: %w", err)
	} else if err == ErrNotDefined {
		return nil, fmt.Errorf("MANGOMAIL_HTTP_RETRY_INTERVAL is required for the mangomail service: %w", err)
	}

	cfg.MaxStartupTime, err = GetMaxStartupTime()
	if err != nil && err != ErrNotDefined {
		return nil, fmt.Errorf("failed to get MANGOMAIL_MAX_STARTUP_TIME: %w", err)
	} else if err == ErrNotDefined {
		return nil, fmt.Errorf("MANGOMAIL_MAX_STARTUP_TIME is required for the mangomail service: %w", err)
	}

	cfg.TelemetryAddress, err = GetTelemetryAddress()
	if err != nil && err != ErrNotDefined {
		return nil, fmt.Errorf("failed to get MANGOMAIL_TELEMETRY_ADDRESS: %w", err)
	} else if err == ErrNotDefined {
		return nil, fmt.Errorf("MANGOMAIL_TELEMETRY_ADDRESS is required for the mangomail service: %w", err)
	}

	cfg.ResendApiKey, err = GetResendApiKey()
	if err != nil && err != ErrNotDefined {
		return nil, fmt.Errorf("failed to get MANGOMAIL_RESEND_API_KEY: %w", err)
	} else if err == ErrNotDefined {
		return nil, fmt.Errorf("MANGOMAIL_RESEND_API_KEY is required for the mangomail service: %w", err)
	}

	cfg.ResendRateLimit, err = GetResendRateLimit()
	if err != nil && err != ErrNotDefined {
		return nil, fmt.Errorf("failed to get MANGOMAIL_RESEND_RATE_LIMIT: %w", err)
	} else if err == ErrNotDefined {
		return nil, fmt.Errorf("MANGOMAIL_RESEND_RATE_LIMIT is required for the mangomail service: %w", err)
	}

	cfg.LogColor, err = GetLogColor()
	if err != nil && err != ErrNotDefined {
		return nil, fmt.Errorf("failed to get MANGOMAIL_LOG_COLOR: %w", err)
	} else if err == ErrNotDefined {
		return nil, fmt.Errorf("MANGOMAIL_LOG_COLOR is required for the mangomail service: %w", err)
	}

	cfg.LogLevel, err = GetLogLevel()
	if err != nil && err != ErrNotDefined {
		return nil, fmt.Errorf("failed to get MANGOMAIL_LOG_LEVEL: %w", err)
	} else if err == ErrNotDefined {
		return nil, fmt.Errorf("MANGOMAIL_LOG_LEVEL is required for the mangomail service: %w", err)
	}

	return &cfg, nil
}

// GetApiKey returns the value for the environment variable MANGOMAIL_API_KEY.
func GetApiKey() (RedactedString, error) {
	s := viper.GetString(API_KEY)
	if s == "" {
		filename := viper.GetString(API_KEY_FILE)
		contents, err := os.ReadFile(filename)
		if err != nil {
			return notDefinedRedactedString(), fmt.Errorf("failed to parse %s: %w", API_KEY_FILE, err)
		}
		s = strings.TrimSpace(string(contents))
	}
	if s != "" {
		v, err := toRedactedString(s)
		if err != nil {
			return v, fmt.Errorf("failed to parse %s: %w", API_KEY, err)
		}
		return v, nil
	}
	return notDefinedRedactedString(), fmt.Errorf("%s: %w", API_KEY, ErrNotDefined)
}

// GetHttpAddress returns the value for the environment variable MANGOMAIL_HTTP_ADDRESS.
func GetHttpAddress() (string, error) {
	s := viper.GetString(HTTP_ADDRESS)
	if s != "" {
		v, err := toString(s)
		if err != nil {
			return v, fmt.Errorf("failed to parse %s: %w", HTTP_ADDRESS, err)
		}
		return v, nil
	}
	return notDefinedstring(), fmt.Errorf("%s: %w", HTTP_ADDRESS, ErrNotDefined)
}

// GetHttpMaxRetries returns the value for the environment variable MANGOMAIL_HTTP_MAX_RETRIES.
func GetHttpMaxRetries() (int, error) {
	s := viper.GetString(HTTP_MAX_RETRIES)
	if s != "" {
		v, err := toInt(s)
		if err != nil {
			return v, fmt.Errorf("failed to parse %s: %w", HTTP_MAX_RETRIES, err)
		}
		return v, nil
	}
	return notDefinedint(), fmt.Errorf("%s: %w", HTTP_MAX_RETRIES, ErrNotDefined)
}

// GetHttpRetryInterval returns the value for the environment variable MANGOMAIL_HTTP_RETRY_INTERVAL.
func GetHttpRetryInterval() (Duration, error) {
	s := viper.GetString(HTTP_RETRY_INTERVAL)
	if s != "" {
		v, err := toDuration(s)
		if err != nil {
			return v, fmt.Errorf("failed to parse %s: %w", HTTP_RETRY_INTERVAL, err)
		}
		return v, nil
	}
	return notDefinedDuration(), fmt.Errorf("%s: %w", HTTP_RETRY_INTERVAL, ErrNotDefined)
}

// GetMaxStartupTime returns the value for the environment variable MANGOMAIL_MAX_STARTUP_TIME.
func GetMaxStartupTime() (Duration, error) {
	s := viper.GetString(MAX_STARTUP_TIME)
	if s != "" {
		v, err := toDuration(s)
		if err != nil {
			return v, fmt.Errorf("failed to parse %s: %w", MAX_STARTUP_TIME, err)
		}
		return v, nil
	}
	return notDefinedDuration(), fmt.Errorf("%s: %w", MAX_STARTUP_TIME, ErrNotDefined)
}

// GetTelemetryAddress returns the value for the environment variable MANGOMAIL_TELEMETRY_ADDRESS.
func GetTelemetryAddress() (string, error) {
	s := viper.GetString(TELEMETRY_ADDRESS)
	if s != "" {
		v, err := toString(s)
		if err != nil {
			return v, fmt.Errorf("failed to parse %s: %w", TELEMETRY_ADDRESS, err)
		}
		return v, nil
	}
	return notDefinedstring(), fmt.Errorf("%s: %w", TELEMETRY_ADDRESS, ErrNotDefined)
}

// GetResendApiKey returns the value for the environment variable MANGOMAIL_RESEND_API_KEY.
func GetResendApiKey() (RedactedString, error) {
	s := viper.GetString(RESEND_API_KEY)
	if s == "" {
		filename := viper.GetString(RESEND_API_KEY_FILE)
		contents, err := os.ReadFile(filename)
		if err != nil {
			return notDefinedRedactedString(), fmt.Errorf("failed to parse %s: %w", RESEND_API_KEY_FILE, err)
		}
		s = strings.TrimSpace(string(contents))
	}
	if s != "" {
		v, err := toRedactedString(s)
		if err != nil {
			return v, fmt.Errorf("failed to parse %s: %w", RESEND_API_KEY, err)
		}
		return v, nil
	}
	return notDefinedRedactedString(), fmt.Errorf("%s: %w", RESEND_API_KEY, ErrNotDefined)
}

// GetResendRateLimit returns the value for the environment variable MANGOMAIL_RESEND_RATE_LIMIT.
func GetResendRateLimit() (int, error) {
	s := viper.GetString(RESEND_RATE_LIMIT)
	if s != "" {
		v, err := toInt(s)
		if err != nil {
			return v, fmt.Errorf("failed to parse %s: %w", RESEND_RATE_LIMIT, err)
		}
		return v, nil
	}
	return notDefinedint(), fmt.Errorf("%s: %w", RESEND_RATE_LIMIT, ErrNotDefined)
}

// GetLogColor returns the value for the environment variable MANGOMAIL_LOG_COLOR.
func GetLogColor() (bool, error) {
	s := viper.GetString(LOG_COLOR)
	if s != "" {
		v, err := toBool(s)
		if err != nil {
			return v, fmt.Errorf("failed to parse %s: %w", LOG_COLOR, err)
		}
		return v, nil
	}
	return notDefinedbool(), fmt.Errorf("%s: %w", LOG_COLOR, ErrNotDefined)
}

// GetLogLevel returns the value for the environment variable MANGOMAIL_LOG_LEVEL.
func GetLogLevel() (LogLevel, error) {
	s := viper.GetString(LOG_LEVEL)
	if s != "" {
		v, err := toLogLevel(s)
		if err != nil {
			return v, fmt.Errorf("failed to parse %s: %w", LOG_LEVEL, err)
		}
		return v, nil
	}
	return notDefinedLogLevel(), fmt.Errorf("%s: %w", LOG_LEVEL, ErrNotDefined)
}
